### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by zhLawliet** [Paper99/SRFBN_CVPR19#1]
when run python test.py -opt options/test/test_SRFBN_example.json
the error is below:
VPR19-master/networks/srfbn_arch.py", line 79, in forward
    LD_H = torch.cat(tuple(hr_features), 1)
RuntimeError: CUDA error: out of memory

i have run the ESRGAN and  SRGAN without the error.

**Comment by Paper99** [comment]
https://github.com/Paper99/SRFBN_CVPR19/blob/0b2f7f4d418f6580fd009a397762021d2deeaf1e/solvers/SRSolver.py#L192

You can decrease `min_size` in this line. I hope it is helpful for you.

**Comment by zhLawliet** [comment]
thanks,  it is ok when i decrease the min_size.
