### ISSUE TITLE
Issue about training on DIV2K and Flickr2K

### ISSUE THREAD

**Issue by Zysty** [Paper99/SRFBN_CVPR19#10]
Hi, thanks for sharing your work.
I'm using windows 10.
I use  the code of EDSR to train SRFBN on 2080Ti GPU.
I always get 'OSError: [Errno 5] Input/output error' when training model on DIV2K and Flickr2K.
and I find it would not happen when training model just on DIV2K.

**Comment by Paper99** [comment]
You need to edit their [dataset file](https://github.com/thstkdgus35/EDSR-PyTorch/blob/master/src/data/div2k.py) to train.

**Comment by Zysty** [comment]
Thanks for your reply. I created a file called 'Flickr2K.py'. But I still encounter the same error.It happens during the model training process. For example, I encountered the error while training the model in the 200th epoch.I am not sure if it is my code problem or the OS problem.

**Comment by Zysty** [comment]
It shows there are 15950 images when training model on DIV2K and Flickr2K. Is it right?

**Comment by Paper99** [comment]
Did you edit the data_range option in [EDSR-Pytorch](https://github.com/thstkdgus35/EDSR-PyTorch/blob/565d6feaf58616558fb01a0c65342c01a3b3a26f/src/option.py#L30)?
The number of images is 800(DIV2K)+2650(Flickr2K).

**Comment by Zysty** [comment]
yes. I use default settings, including batch_size=16,test_every=1000.So the terminal shows that the length of train dataset is 16000(repeat=20) if I train model on DIV2K. And The length of train dataset is 15950 if I train model on DIV2K(8000, repeat=10) and Flickr2K(7950, repeat=3).I am not sure whether I edit dataset file correctly.

**Comment by Paper99** [comment]
I suggest you directly use our code to train, or you can replace the dataset file in EDSR-Pytorch using our dataset file (need to edit some options).

**Comment by Zysty** [comment]
OK.I will try it.Sincerely thank you for your reply.

**Comment by Zysty** [comment]
Hi, 
I have read your code.I find that what you want to do  is to put DIV2K and Flickr2K  in the same LR file before running program.So the LR file has 3450 images. But what EDSR does is that using ConcatDataset from torch.utils.data to concatenate the two datasets. So it shows 15950 images(or iterations) when training model. Can you tell me the number of iterations in each epoch when you train your model?
Thanks a lot.

**Comment by Paper99** [comment]
About 1000 iterations

**Comment by Zysty** [comment]
I got it.Thanks.

**Comment by Zysty** [comment]
I got it.Thanks.
