### ISSUE TITLE
Hello,when i set pretrain=true and train,folder will be renamed and a new folder willbe created,have u met this problem???thx

### ISSUE THREAD

**Issue by SeriouslyHAO** [Paper99/SRFBN_CVPR19#12]

**Comment by Paper99** [comment]
If you want to continue your training progress, you can set `"pretrain"` to `"resume"`. This will not create a new folder.
We regard the finetuned models as new trained models (when `"pretrain"` is set to `"finetune"` ), so a new folder will be created.

**Comment by SeriouslyHAO** [comment]
thx

**Comment by SeriouslyHAO** [comment]
thx
