### ISSUE TITLE
why use offline data-augmentation?

### ISSUE THREAD

**Issue by apxlwl** [Paper99/SRFBN_CVPR19#13]
why use offline data-augmentation instead of online?

**Comment by Paper99** [comment]
Because DIV2K+Flickr2K dataset is too large, we only employed online data-augmentation for training final models.

**Comment by apxlwl** [comment]
> Because DIV2K+Flickr2K dataset is too large, we only employed online data-augmentation for training final models.

Thankyou for your reply. But you prepare the multiscale training pairs offline via matlab scripts. Why dont you also do it online?

**Comment by Paper99** [comment]
When we training final models, we **directly** downsampled the training images. No offline data-augmentation was used. The matlab script may confuses you. We're sorry about that. We will update it for choosing offline data-augmentation optionally .

**Comment by apxlwl** [comment]
> When we training final models, we **directly** downsampled the training images. No offline data-augmentation was used. The matlab script may confuses you. We're sorry about that. We will update it for choosing offline data-augmentation optionally .
Thank you. So you first transfer the image file into numpy format? Can this operation accelerate the data loading?

**Comment by Paper99** [comment]
Yes

**Comment by Paper99** [comment]
It may be a better choice than lmdb data format
