### ISSUE TITLE
The inconsistency between the code and your paper

### ISSUE THREAD

**Issue by peter850706** [Paper99/SRFBN_CVPR19#3]
Hi, first thanks for your excellent work. I have noticed that the code of the [LR feature extraction block](https://github.com/Paper99/SRFBN_CVPR19/blob/master/networks/srfbn_arch.py#L132) use a 1x1 conv layer, but the Figure 2. in your paper shows that it uses a 3x3 conv layer, maybe it's a typo in your paper?

**Comment by Paper99** [comment]
Thank you for pointing out the mistake in our paper. We will fix it in the next arXiv version.
