### ISSUE TITLE
How do you specify a specific HR to a given Feedback block

### ISSUE THREAD

**Issue by charles-bonnineau** [Paper99/SRFBN_CVPR19#30]
Hey, 

First, thank you very much for this amazing paper. In my case, I would like to train the model for other degradation methods than the ones presented in your work. If I have well understood, for complex degradation models the complexity of the HR ground truth increase over feedback iterations. However, I don't see any option to specify ground truth at feedback-block level. Is there any way to do this with your code ?
 
Thank you in advance and have a nice day,
Charles

**Comment by Paper99** [comment]
Hey,

Current code has not implemented the support for different HR targets. You can add option(s) in `.json`, and edit the files including `LRHRdataset.py` and `SRSolver.py` for such purpose.

**Comment by charles-bonnineau** [comment]
Okay thanks !
