### ISSUE TITLE
Speed of this method

### ISSUE THREAD

**Issue by bittergourd1224** [Paper99/SRFBN_CVPR19#40]
Hi, there. I have seen that the speed of your method is really fast compared to the other methods according to the last pages of your paper. Have you compared your method with SRCNN or FSRCNN, which claimed to be 40 times faster than SRCNN?

**Comment by Paper99** [comment]
We didn't implement SRCNN and FSRCNN on Pytorch framework. But if you re-implement SRCNN or FSRCNN on Pytorch (with CUDA available), you will find that their running speed is much more faster~~ than their paper reported which was tested on **CPU** using their C++ version. And I believe that the speed of SRCNN and FSRCNN implemented on Pytorch will be faster than ours.

**Comment by bittergourd1224** [comment]
Thank you very much for your fast replies! So it's a weigh of speed and correctness I guess.
