### ISSUE TITLE
PyTorch 0.4.0: module 'torch.nn.functional' has no attribute 'interpolate'

### ISSUE THREAD

**Issue by Mukosame** [Paper99/SRFBN_CVPR19#5]
This function is introduced in PyTorch 0.4.1 (https://github.com/1adrianb/face-alignment/issues/110#issuecomment-438074180)

You can specify the pytorch version >= 0.4.1 in readme.md

**Comment by Paper99** [comment]
Thank you for pointing out this. According to your mentioned problem, we have edited `README.md` and [`networks/srfbn_arch.py`](https://github.com/Paper99/SRFBN_CVPR19/blob/96845472392eacfe09a1caf996be5498ce060e06/networks/srfbn_arch.py#L139).
