### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by yinyiyu** [Paper99/SRFBN_CVPR19#50]
Thanks for your great work。I trained on my own dataset for x8 scale，but when I try to test is，I got an error。
![image](https://user-images.githubusercontent.com/24800963/79241223-5a6cba00-7ea5-11ea-9cf1-6fda4ee3d245.png)
It looks like the data size in chechpoint is half in the model

**Comment by Paper99** [comment]
Please check the `num_features` option in your `test_xxx.json` file.

**Comment by yinyiyu** [comment]
Thank you, yes. I use the setting 32 for training，but 64 for testing . After I change it to 32 ,it works.That is, does the configuration of the networks must be the same  for testing and training .

**Comment by Paper99** [comment]
Yes, you're right.
