### ISSUE TITLE
question about srfbn-arch.py

### ISSUE THREAD

**Issue by Senwang98** [Paper99/SRFBN_CVPR19#56]
Hi, paper99
I'm reading your paper and code recently. However, I feel confused about some code in your srfbn-arch.py/SRFBN/forward:

```python
        outs = []
        for _ in range(self.num_steps):
            h = self.block(x)

            h = torch.add(inter_res, self.conv_out(self.out(h)))
            h = self.add_mean(h)
            outs.append(h)
```

I have no idea if you have removed some codes here, because I think the output **h** is always the same(**that's to say all elements in outs are all the same**). Can you give me some suggestions?
Wishing for your reply!

**Comment by qixicccc** [comment]
I also found this problem. Have you solved it？
