### ISSUE TITLE
About retraining BD/DN model of vdsr and srcnn 

### ISSUE THREAD

**Issue by yyknight** [Paper99/SRFBN_CVPR19#7]
Thanks for your impressive work. You mentioned that you retrained VDSR and SRCNN for BD/DN model. Could you tell me that you strictly followed the original settings and retrained the VDSR, SRCNN model? or simply use same settings as your main methods but the structure?

**Comment by Paper99** [comment]
For SRCNN, we used the official code for training on BD and DN degradation models.
For VDSR, we used [vdsr-caffe](https://github.com/huangzehao/caffe-vdsr) for training (**reason**: No official training implementation).
Except degradation models, all settings strictly followed SRCNN/VDSR paper.

**Comment by yyknight** [comment]
Thanks for your reply! So you implement bicubic interpolation on the generated DN/BD LR images to get the LR training images for  VDSR/SRCNN?

**Comment by Paper99** [comment]
Yes.

**Comment by yyknight** [comment]
OK, I got it. Thanks.
