### ISSUE TITLE
About inference time that mentioned in Section D of Supplementary Material

### ISSUE THREAD

**Issue by zzzzwj** [Paper99/SRFBN_CVPR19#9]
I can't reproduce the average inference time that reported as 0.011s on the benchmark Urban100 with an Nvidia GTX1080Ti GPU. In my case, it needs about 0.4s (just inference time) to make a super resolution picture.

**Comment by Paper99** [comment]
The inference time can vary a lot according to the CPU. We use 4.2GHz Intel i7 CPU to obtain the results.

**Comment by zzzzwj** [comment]
Why? The inference process only runs on GPU I think. As far as I know, the CPU frequency only affects the time of data preparation which is excluded when computing the time consumed.

**Comment by zzzzwj** [comment]
And thanks for your reply.

**Comment by Paper99** [comment]
I am also confused about it. We took forward test on different machines with same environment except for the types of CPU, but the results varied a lot.

**Comment by zzzzwj** [comment]
Thank you anyway though I'm also confused.
